services:
  kafka-kraft:
    image: confluentinc/cp-kafka:7.7.1
    hostname: kafka-kraft
    container_name: kafka-kraft
    ports:
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-kraft:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-kraft:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka-kraft:29092,CONTROLLER://kafka-kraft:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: q1Sh-9_ISia_zwGINzRvyQ
      KAFKA_CREATE_TOPICS: "sinc_topic:1:1"

  emqx-enterprise:
    image: emqx/emqx-enterprise:5.8.1
    container_name: emqx
    healthcheck:
      test: [ "CMD", "emqx", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 12
    ports:
      - 1883:1883
      - 18083:18083
    volumes:
      - $PWD/emqx_bridges.hocon:/opt/emqx/data/configs/cluster.hocon
    depends_on:
      - kafka-kraft

  mqttx-simulate:
    image: emqx/mqttx-cli:v1.9.3
    container_name: mqttx-simulate_iem
    command:
      - /bin/sh
      - -c
      - |
        mqttx simulate -sc IEM -c 1000 -h emqx-enterprise
    depends_on:
      emqx-enterprise:
        condition: service_healthy

  mqttx:
    image: emqx/mqttx-cli:v1.9.3
    container_name: mqttx
    command:
      - /bin/sh
      - -c
      - |
        mqttx sub -t 'mqttx/simulate/#' -v -h emqx-enterprise
    depends_on:
      emqx-enterprise:
        condition: service_healthy

networks:
  emqx-net:
    name: emqx-net



